Section "ServerFlags"
    Option "AutoAddGPU" "false"
EndSection

Section "Device"
    Identifier "VirtIO GPU"
    Driver "modesetting"
    BusID "PCI:0:13:0"
    Option "AccelMethod" "none"
    Option "SWcursor" "on"
    Option "PrimaryGPU" "true"
EndSection

Section "Screen"
    Identifier "VirtIO Screen"
    Device "VirtIO GPU"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
        Modes "1024x768"
    EndSubSection
EndSection

Section "ServerLayout"
    Identifier "VirtIO Layout"
    Screen 0 "VirtIO Screen"
EndSection
