/* Generated by generate-fixtures.js. */
static const struct scene_definition SCENES[] = {
    { "ramps", "ramps.ppm", 256, 12, SCALE_NEAREST, "22318e0d3d695b263d2dbc8c6808106dfbcef1091b6684f3d2fd2b967de5a1c1", "45c446e83cffb12c64dff229a1a93d64809d16828488586e9990285cea438c73" },
    { "palette", "palette.ppm", 64, 64, SCALE_NEAREST, "2163a4097f6fb9c65610491bbbc71b12e579df1572e686a0e1e2513efaeeb980", "13fcff52a27eb6e0d2a2a62d2d2a348c8166d1aabb3db283b911f5f45547d0be" },
    { "smpte", "smpte.ppm", 1024, 3, SCALE_SMPTE_BANDS, "d5742819fd131ea446f19d002af464a8fd499d3a85294b737db7630aed93c7f8", "a10c1021f8676a794ee2154dc5bac7b08ae2403d7e26ad785d3f3af0f73a5b14" },
    { "photo_blue_marble", "photo_blue_marble.ppm", 256, 192, SCALE_NEAREST, "cacda93dc7cd7316b88a8b138b31924feedf0a9fe627e34345172202bb834dc8", "9b8fd215024e29a71238a031bfb551df719e672c8272973e088b256d7a510e6f" },
    { "photo_tokyo", "photo_tokyo.ppm", 256, 192, SCALE_NEAREST, "0cf72163927377d06dd46d4eb59584f60decbe8cc6431fd13097c91cda99bbf4", "f32a37107be9831c735adb6d6689d6ad8ff399d52ae9ffbf34a321a688a5afa6" },
};
